<a href="https://colab.research.google.com/github/tlooden/BMS13/blob/main/BMS13python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Material for introduction to python for BMS-13. 

Author: Tristan Looden

In [ ]:
# Commenting in python can be done using the hastag

import numpy as np
import matplotlib.pyplot as plt


In [ ]:
# define a one-dimensional array of numbers (ie, a vector)

some_numbers = [1,2,3,4]


some_vector = np.array(some_numbers)


print(some_vector)

[[1 2 3 4]]


In [ ]:
# define a two-dimensional array of numbers (ie, a matrix)

some_matrix = np.array([ [1,2] ,[3,4] ])

print(some_matrix)

[[1 2]
 [3 4]]


In [ ]:
b= np.array([1,2])

result = b*some_matrix

print(result)

[[ 7 10]]


In [ ]:
for i in some_number:
  print(i)

1
2


In [ ]:
def my_sum(A):
  out = np.sum(A)
  return out

In [ ]:
result = my_sum(some_matrix)

print(result)

10
